### get mission by id
# @prompt mission_id Mission ID
GET  {{base_url}}/mission-viewing/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}




### get missions with name
# @prompt name Name to Search
GET  {{base_url}}/mission-viewing/gets?name={{name}}
Content-Type: application/json
Authorization: Bearer {{access_token}}


### get missions with name and status
# @prompt name Name to Search
# @prompt status Status to Search
GET  {{base_url}}/mission-viewing/gets?name={{name}}&status={{status}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
