import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'en' | 'th';

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    currentLang = signal<Lang>('en');

    // Translations dictionary
    private dict: Record<Lang, Record<string, string>> = {
        en: {
            // Navbar
            'nav.missions': 'Missions',
            'nav.my_created': 'My Created',
            'nav.my_joined': 'My Joined',
            'nav.logout': 'Logout',
            'nav.login': 'Login',

            // Home
            'home.welcome': 'Greetings,',
            'home.subtitle': 'Many new missions are waiting for Brawlers to conquer today.',
            'home.find_mission': 'Find New Missions',
            'home.create_mission': 'Create Mission',
            'home.stat.created': 'Created',
            'home.stat.joined': 'Joined',
            'home.stat.completed': 'Completed',
            'home.activity.title': 'Recent Activities',
            'home.activity.empty': 'No new notifications at this time.',
            'home.trending.title': 'Latest Trending Missions',
            'home.profile.view': 'View My Profile',
            'home.activity.created': 'has announced a new mission:',
            'home.activity.started': 'has started working on:',
            'home.activity.completed': 'has successfully completed:',
            'home.activity.failed': 'has failed the mission:',
            'home.guest.title': 'UNAUTHORIZED_ACCESS',
            'home.guest.subtitle': 'Global operations feed is active. Full system access requires biometric authentication.',
            'home.guest.cta': 'ENLIST_NOW',
            'home.guest.login': 'ACCESS_TERMINAL',

            // Profile
            'profile.title': 'User Profile',
            'profile.welcome': 'Welcome to your profile!',
            'profile.id': 'User ID',
            'profile.display_name': 'Display Name',
            'profile.username': 'Username',

            // Missions
            'missions.title': 'All Missions',
            'missions.search': 'Search',
            'missions.all_statuses': 'All Statuses',
            'missions.status.open': 'Open',
            'missions.status.completed': 'Completed',
            'missions.status.in_progress': 'In Progress',
            'missions.status.inprogress': 'In Progress',
            'missions.status.failed': 'Failed',
            'missions.search.placeholder': 'Search by name...',
            'missions.go': 'Go',
            'missions.table.name': 'Name',
            'missions.table.description': 'Description',
            'missions.table.creator': 'Creator',
            'missions.table.crew': 'Crew',
            'missions.table.status': 'Status',
            'missions.table.created': 'Created at',
            'missions.table.updated': 'Updated at',
            'missions.table.actions': 'Actions',
            'missions.action.join': 'Join',
            'missions.action.leave': 'Leave',
            'missions.action.view': 'View Details',
            'missions.action.load_more': 'Load More Missions',
            'missions.empty': 'No missions found matching the filter.',

            // Mission Manager (My Created)
            'manager.title': 'My Missions',
            'manager.subtitle': 'Manage and track the missions you\'ve created.',
            'manager.new': 'New Mission',
            'manager.action.edit': 'Edit Details',
            'manager.action.start': 'Start Mission',
            'manager.action.complete': 'Complete',
            'manager.action.fail': 'Fail',
            'manager.action.delete': 'Delete',
            'manager.action.view_report': 'View Summary Report',
            'manager.empty.title': 'No Missions Found',
            'manager.empty.subtitle': 'You haven\'t created any missions yet.',

            // Joined Missions
            'joined.title': 'Joined Missions',
            'joined.subtitle': 'Missions you are currently participating in.',

            // Dialogs
            'dialog.new_mission.title': 'Create New Mission',
            'dialog.new_mission.subtitle': 'Fill in the details to start a new mission.',
            'dialog.edit_mission.title': 'Edit Mission',
            'dialog.edit_mission.subtitle': 'Update the details of your mission.',
            'dialog.mission_name.label': 'Mission Name',
            'dialog.mission_name.placeholder': 'What is this mission called?',
            'dialog.description.label': 'Description',
            'dialog.description.placeholder': 'Tell us more about the mission goals...',
            'dialog.actions.create': 'Create',
            'dialog.crew_limit.label': 'Crew Limit',
            'dialog.crew_limit.hint': 'Please specify between 2 to 10 members.',
            'dialog.actions.update': 'Update',
            'dialog.delete_mission.title': 'Delete Mission',
            'dialog.delete_mission.message': 'Are you sure you want to delete mission "{{name}}"? This action cannot be undone.',
            'dialog.fail_mission.title': 'Fail Mission',
            'dialog.fail_mission.message': 'Mark mission "{{name}}" as Failed?',
            'dialog.alert.no_crew_delete': 'Cannot delete mission with active crew members.',
            'dialog.alert.no_crew_start': 'Cannot start mission with 0 crew members. At least 1 member is required.',
            'mission.chat.title': 'Mission Chat',
            'mission.chat.empty': 'No messages yet. Start the conversation!',
            'mission.chat.guest_empty': 'No messages yet.',
            'mission.chat.input_placeholder': 'Type a message...',
            'mission.chat.send': 'Send',
            'mission.crew': 'Crew',

            // Common
            'common.cancel': 'Cancel',
            'common.save': 'Save Changes',
            'common.confirm': 'Confirm',
            'common.guest': 'Guest',
            'common.crew_member': 'Crew Member',
            'common.crew_count': '{{count}} crew',

            // Login/Register
            'auth.title.login': 'Login',
            'auth.title.register': 'Register',
            'auth.username': 'Username',
            'auth.username.placeholder': 'Type your username',
            'auth.display_name': 'aka name',
            'auth.display_name.placeholder': 'Type your aka name',
            'auth.password': 'Password',
            'auth.password.placeholder': 'Type your password',
            'auth.confirm_password': 'Confirm Password',
            'auth.confirm_password.placeholder': 'Confirm your password',
            'auth.or': 'or',
            'auth.new_user': 'New to Kevin?',
            'auth.already_have_account': 'Already have an account?',
            'auth.error.required': 'required',
            'auth.error.min_length': 'must be at least {{length}} characters',
            'auth.error.max_length': 'must be at most {{length}} characters',
            'auth.error.invalid_length': 'must be {{min}} - {{max}} characters long',
            'auth.error.mismatch': 'Passwords do not match',
            'dialog.leave_mission.title': 'Leave Mission',
            'dialog.leave_mission.message': 'Are you sure you want to leave mission "{{name}}"?',
            'mission.chat.login_to_chat': 'Login to Chat',
            'mission.crew.empty': 'No crew members yet.',
            'auth.error.not_found': 'Invalid username or password',
            'auth.error.server': 'Server error, please try again later',
            'auth.welcome_back': 'Welcome back, {{name}}!',
            'auth.register_success': 'Account created! Welcome, {{name}}!',
            'auth.logout.title': 'TERMINATE_SESSION',
            'auth.logout.message': 'Are you sure you want to disconnect from the mission hub? Active signals will be masked.',
            'auth.logout.syncing': 'SYNCING_OPERATIONAL_DATA...',
            'auth.logout.clearing': 'ERASING_TERMINAL_TRACE...',
            'auth.logout.confirm': 'DISCONNECT',

            // HUD / Tactical
            'hud.signal_lost': 'SIGNAL_LOST',
            'hud.area_unreachable': 'AREA_UNREACHABLE',
            'hud.re_acquire_signal': 'RE-ACQUIRE_HUB_SIGNAL',
            'hud.not_found_desc': 'COORDINATES_POINT_TO_VOID. TERMINAL_CONNECTION_TIMED_OUT. STAY_WITHIN_OPS_PARA_BOUNDARY_V1.04.',
            'hud.system_critical': 'SYSTEM_CRITICAL',
            'hud.breach_detected': 'BREACH_DETECTED',
            'hud.server_error_desc': 'DATABASE_ENCRYPTION_MALFUNCTION. UNAUTHORIZED_ACCESS_ATTEMPT_DETECTED_IN_SECTOR_7.',
            'hud.err_code': '[ERR_CODE: {{code}}]',
            'hud.re_initialize': 'RE-INITIALIZE_SYSTEM',
            'hud.auth_required': '[AUTHORIZATION_REQUIRED]',
            'hud.awaiting_input': 'SYSTEM_AWAITING_INPUT...',
            'hud.biometric_interface': 'BIOMETRIC_INTERFACE_V2',
            'hud.re_scan': 'RE-SCAN_BIOMETRICS',
            'hud.initialize_scan': 'INITIALIZE_SCAN',
            'hud.sync_profile': 'SYNC_PROFILE',
            'hud.mod_op_data': 'MOD_OP_DATA_S04',
            'hud.processing': 'PROCESSING...',
            'hud.uploading': 'UPLOADING...',
            'hud.biometric_active': 'BIOMETRIC_VERIFICATION_ACTIVE',
            'hud.matching_id': 'MATCHING_IDENTITY_DB...',
            'hud.redirecting_hub': 'Redirecting to mission hub...',
            'mission.join_to_chat': 'Join this mission to participate in the chat.',
            'mission.chat_restricted': 'Mission in progress. Chat restricted to crew members.',
            'mission.chat_closed': 'Mission has ended. Chat is closed for non-members.',
            'mission.no_intel': 'NO_INTEL_THREADS_FOUND',
            'mission.waiting_comm': 'WAITING_FOR_OPERATOR_COMMUNICATION...',
            'hud.uplink_analysis': 'UPLINK_ANALYSIS // ENCRYPTED_STREAM',
            'hud.target_location': 'TARGET_LOCATION',
            'hud.intel_stream': 'INCOMING_INTEL_STREAM...',
            'hud.sync_orbital': 'SYNCING_ORBITAL_PHASE... [OK]',
            'hud.signal_strength': 'SIGNAL_STRENGTH',
            'hud.active_encryption': 'ACTIVE_ENCRYPTION',
            'alert.failed_send_msg': 'Failed to send message',
            'alert.failed_join': 'Failed to join mission',
            'alert.failed_leave': 'Failed to leave mission',
            'alert.mission_not_found': 'Mission not found or has been deleted.',

            // New Home HUD Keys
            'home.hud.op_online': 'OPERATOR_ONLINE',
            'home.hud.id_token': 'ID_TOKEN',
            'home.hud.top_missions': 'TOP_MISSION_SIGNALS',
            'home.hud.access_all': 'ACCESS_ALL_INTEL',
            'home.hud.live_comms': 'LIVE_COMM_CHANNEL',
            'home.hud.waiting_uplink': 'WAITING_FOR_UPLINK...',
            'home.hud.access_denied': 'ACCESS_DENIED',
            'home.hud.access_denied_desc': 'SYSTEM_ENCRYPTION_ACTIVE. UNAUTHORIZED_PERSONNEL_MUST_IDENTIFY_IMMEDIATELY.',
            'home.hud.authorize': 'AUTHORIZE',
            'home.hud.callout.op_verified': 'OP_ID_VERIFIED',
            'home.hud.callout.data_sync': 'DATA_SYNC_ACTIVE',
            'home.hud.callout.intel_uplink': 'STRAT_INTEL_UPLINK',
            'home.hud.callout.signal_encrypted': 'SIGNAL_ENCRYPTED',
            'home.hud.guest_user': 'GUEST_USER',
            'home.hud.not_found': 'NOT_FOUND',

            'aar.title': 'AFTER_ACTION_REPORT',
            'aar.top_secret': '[TOP_SECRET]',
            'aar.authorized_by': 'AUTHORIZED_BY:',
            'aar.acknowledge': 'ACKNOWLEDGE_ENTRY',
            'aar.debrief': '[OPERATIONAL_DEBRIEF]',
            'aar.mission_name': 'MISSION_NAME',
            'aar.final_status': 'FINAL_STATUS',
            'aar.personnel_log': '[PERSONNEL_LOG]',
            'aar.commander': 'COMMANDER',
            'aar.active_crew': 'ACTIVE_CREW',
            'aar.no_crew': 'NO_CREW_DETECTED',
            'aar.hq_comms': '[HQ_COMMS]',
            'aar.success_msg': 'OPERATION_SUCCESS. ALL_ASSETS_EXTRACTED.',
            'aar.failure_msg': 'OPERATION_FAILURE. INITIATING_FALLBACK.'
        },
        th: {
            // Navbar
            'nav.missions': 'ภารกิจทั้งหมด',
            'nav.my_created': 'ภารกิจที่สร้าง',
            'nav.my_joined': 'ภารกิจที่เข้าร่วม',
            'nav.logout': 'ออกจากระบบ',
            'nav.login': 'เข้าสู่ระบบ',

            // Home
            'home.welcome': 'สวัสดี,',
            'home.subtitle': 'วันนี้มีภารกิจใหม่ๆ รอให้เหล่าบราวเลอร์มาพิชิตเพียบเลย',
            'home.find_mission': 'หาภารกิจใหม่',
            'home.create_mission': 'สร้างภารกิจ',
            'home.stat.created': 'ที่สร้างเอง',
            'home.stat.joined': 'ที่เข้าร่วม',
            'home.stat.completed': 'สำเร็จแล้ว',
            'home.activity.title': 'บันทึกความเคลื่อนไหวล่าสุด',
            'home.activity.empty': 'ยังไม่มีข้อความแจ้งเตือนใหม่ในขณะนี้',
            'home.trending.title': 'ภารกิจยอดฮิตล่าสุด',
            'home.profile.view': 'ดูโปรไฟล์ของฉัน',
            'home.activity.created': 'ได้สร้างภารกิจใหม่:',
            'home.activity.started': 'เริ่มทำภารกิจ:',
            'home.activity.completed': 'ทำภารกิจสำเร็จแล้ว!:',
            'home.activity.failed': 'ทำภารกิจไม่สำเร็จ:',
            'home.guest.title': 'ไม่พบตัวตนในระบบ',
            'home.guest.subtitle': 'คุณกำลังดูข้อมูลสาธารณะ กรุณายืนยันตัวตนเพื่อเข้าถึงระบบปฏิบัติการเต็มรูปแบบ',
            'home.guest.cta': 'ลงทะเบียนร่วมทีม',
            'home.guest.login': 'เข้าสู่ระบบ',

            // Profile
            'profile.title': 'โปรไฟล์ผู้ใช้งาน',
            'profile.welcome': 'ยินดีต้อนรับสู่โปรไฟล์ของคุณ!',
            'profile.id': 'รหัสผู้ใช้งาน',
            'profile.display_name': 'ชื่อที่แสดง',
            'profile.username': 'ชื่อผู้ใช้งาน',

            // Missions
            'missions.title': 'ภารกิจทั้งหมด',
            'missions.search': 'ค้นหา',
            'missions.all_statuses': 'ทุกสถานะ',
            'missions.status.open': 'เปิดรับ',
            'missions.status.completed': 'สำเร็จ',
            'missions.status.in_progress': 'กำลังทำ',
            'missions.status.inprogress': 'กำลังทำ',
            'missions.status.failed': 'ไม่สำเร็จ',
            'missions.search.placeholder': 'ค้นหาด้วยชื่อ...',
            'missions.go': 'ค้นหา',
            'missions.table.name': 'ชื่อ',
            'missions.table.description': 'รายละเอียด',
            'missions.table.creator': 'ผู้สร้าง',
            'missions.table.crew': 'ลูกเรือ',
            'missions.table.status': 'สถานะ',
            'missions.table.created': 'สร้างเมื่อ',
            'missions.table.updated': 'อัปเดตเมื่อ',
            'missions.table.actions': 'จัดการ',
            'missions.action.join': 'เข้าร่วม',
            'missions.action.leave': 'ออก',
            'missions.action.view': 'ดูข้อมูล',
            'missions.action.load_more': 'โหลดภารกิจเพิ่มเติม',
            'missions.empty': 'ไม่พบภารกิจที่ตรงตามตัวกรอง',

            // Mission Manager (My Created)
            'manager.title': 'ภารกิจของฉัน',
            'manager.subtitle': 'จัดการและติดตามภารกิจที่คุณสร้างขึ้น',
            'manager.new': 'ภารกิจใหม่',
            'manager.action.edit': 'แก้ไขรายละเอียด',
            'manager.action.start': 'เริ่มภารกิจ',
            'manager.action.complete': 'สำเร็จ',
            'manager.action.fail': 'ไม่สำเร็จ',
            'manager.action.delete': 'ลบภารกิจ',
            'manager.action.view_report': 'ดูสรุปผล',
            'manager.empty.title': 'ไม่พบภารกิจ',
            'manager.empty.subtitle': 'คุณยังไม่ได้สร้างภารกิจใดๆ',

            // Joined Missions
            'joined.title': 'ภารกิจที่เข้าร่วม',
            'joined.subtitle': 'ภารกิจที่คุณกำลังดำเนินการในขณะนี้',

            // Dialogs
            'dialog.new_mission.title': 'สร้างภารกิจใหม่',
            'dialog.new_mission.subtitle': 'กรอกรายละเอียดเพื่อเริ่มภารกิจใหม่',
            'dialog.edit_mission.title': 'แก้ไขภารกิจ',
            'dialog.edit_mission.subtitle': 'อัปเดตรายละเอียดภารกิจของคุณ',
            'dialog.mission_name.label': 'ชื่อภารกิจ',
            'dialog.mission_name.placeholder': 'ภารกิจนี้ชื่ออะไร?',
            'dialog.description.label': 'รายละเอียด',
            'dialog.description.placeholder': 'บอกรายละเอียดหรือเป้าหมายของภารกิจ...',
            'dialog.actions.create': 'สร้าง',
            'dialog.crew_limit.label': 'จำนวนลูกเรือสูงสุด',
            'dialog.crew_limit.hint': 'กรุณาระบุจำนวน 2 ถึง 10 คน',
            'dialog.actions.update': 'อัปเดต',
            'dialog.delete_mission.title': 'ลบภารกิจ',
            'dialog.delete_mission.message': 'คุณแน่ใจหรือไม่ว่าต้องการลบภารกิจ "{{name}}"? การดำเนินการนี้ไม่สามารถย้อนกลับได้',
            'dialog.fail_mission.title': 'ภารกิจล้มเหลว',
            'dialog.fail_mission.message': 'ตั้งสถานะภารกิจ "{{name}}" เป็นล้มเหลวใช่หรือไม่?',
            'dialog.alert.no_crew_delete': 'ไม่สามารถลบภารกิจที่มีลูกเรืออยู่ได้',
            'dialog.alert.no_crew_start': 'ไม่สามารถเริ่มภารกิจที่มีลูกเรือ 0 คนได้ จำเป็นต้องมีอย่างน้อย 1 คน',
            'mission.chat.title': 'ห้องแชทภารกิจ',
            'mission.chat.empty': 'ยังไม่มีข้อความ เริ่มบทสนทนาได้เลย!',
            'mission.chat.guest_empty': 'ยังไม่มีข้อความ',
            'mission.chat.input_placeholder': 'พิมพ์ข้อความ...',
            'mission.chat.send': 'ส่ง',
            'mission.crew': 'ลูกเรือ',

            // Common
            'common.cancel': 'ยกเลิก',
            'common.save': 'บันทึกการเปลี่ยนแปลง',
            'common.confirm': 'ยืนยัน',
            'common.guest': 'ผู้เยี่ยมชม',
            'common.crew_member': 'สมาชิกลูกเรือ',
            'common.crew_count': 'ลูกเรือ {{count}} คน',

            // Themes
            'theme.light': 'สว่าง',
            'theme.dark': 'มืด',
            'theme.royal': 'หรูหรา',

            // Login/Register
            'auth.title.login': 'เข้าสู่ระบบ',
            'auth.title.register': 'ลงทะเบียน',
            'auth.username': 'ชื่อผู้ใช้งาน',
            'auth.username.placeholder': 'พิมพ์ชื่อผู้ใช้งานของคุณ',
            'auth.display_name': 'ชื่อที่แสดง (นามแฝง)',
            'auth.display_name.placeholder': 'พิมพ์ชื่อนามแฝงของคุณ',
            'auth.password': 'รหัสผ่าน',
            'auth.password.placeholder': 'พิมพ์รหัสผ่านของคุณ',
            'auth.confirm_password': 'ยืนยันรหัสผ่าน',
            'auth.confirm_password.placeholder': 'พิมพ์ยืนยันรหัสผ่านอีกครั้ง',
            'auth.or': 'หรือ',
            'auth.new_user': 'ยังไม่มีบัญชีใช่ไหม?',
            'auth.already_have_account': 'มีบัญชีอยู่แล้ว?',
            'auth.error.required': 'กรุณากรอกข้อมูล',
            'auth.error.min_length': 'อย่างน้อย {{length}} ตัวอักษร',
            'auth.error.max_length': 'ไม่เกิน {{length}} ตัวอักษร',
            'auth.error.invalid_length': 'ต้องมีความยาว {{min}} - {{max}} ตัวอักษร',
            'auth.error.mismatch': 'รหัสผ่านไม่ตรงกัน',
            'dialog.leave_mission.title': 'ออกจากภารกิจ',
            'dialog.leave_mission.message': 'คุณแน่ใจหรือไม่ว่าต้องการออกจากภารกิจ "{{name}}"?',
            'mission.chat.login_to_chat': 'เข้าสู่ระบบเพื่อพูดคุย',
            'mission.crew.empty': 'ยังไม่มีลูกเรือในขณะนี้',
            'auth.error.not_found': 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
            'auth.error.server': 'เกิดข้อผิดพลาดที่เซิร์ฟเวอร์ กรุณาลองใหม่ภายหลัง',
            'auth.welcome_back': 'ยินดีต้อนรับกลับมา, {{name}}!',
            'auth.register_success': 'สร้างบัญชีสำเร็จ! ยินดีต้อนรับ, {{name}}!',
            'auth.logout.title': 'ตัดการเชื่อมต่อ',
            'auth.logout.message': 'คุณแน่ใจไหมว่าต้องการปิดระบบ? ข้อมูลการเชื่อมต่อทั้งหมดจะถูกลบออกเพื่อความปลอดภัย',
            'auth.logout.syncing': 'กำลังบันทึกข้อมูล...',
            'auth.logout.clearing': 'กำลังเคลียร์ร่องรอย...',
            'auth.logout.confirm': 'ตัดการเชื่อมต่อ',

            // HUD / Tactical
            'hud.signal_lost': 'สัญญาณขาดหาย',
            'hud.area_unreachable': 'พื้นที่เข้าถึงไม่ได้',
            'hud.re_acquire_signal': 'เชื่อมต่อสัญญาณใหม่',
            'hud.not_found_desc': 'พิกัดเป็นพื้นที่ว่าง. การเชื่อมต่อเทอร์มินัลหมดเวลา. กรุณาอยู่ภายในขอบเขตปฏิบัติการ V1.04',
            'hud.system_critical': 'ระบบวิกฤต',
            'hud.breach_detected': 'ตรวจพบการบุกรุก',
            'hud.server_error_desc': 'ระบบเข้ารหัสฐานข้อมูลผิดพลาด. ตรวจพบความพยายามเข้าถึงที่ไม่ได้รับอนุญาตในเซกเตอร์ 7',
            'hud.err_code': '[รหัสข้อผิดพลาด: {{code}}]',
            'hud.re_initialize': 'เริ่มระบบใหม่',
            'hud.auth_required': '[จำเป็นต้องมีการอนุมัติ]',
            'hud.awaiting_input': 'ระบบกำลังรอคำสั่ง...',
            'hud.biometric_interface': 'อินเตอร์เฟซชีวภาพ V2',
            'hud.re_scan': 'สแกนข้อมูลชีวภาพใหม่',
            'hud.initialize_scan': 'เริ่มการสแกน',
            'hud.sync_profile': 'ซิงค์โปรไฟล์',
            'hud.mod_op_data': 'แก้ไขข้อมูลปฏิบัติการ S04',
            'hud.processing': 'กำลังประมวลผล...',
            'hud.uploading': 'กำลังอัปโหลด...',
            'hud.biometric_active': 'กำลังตรวจสอบข้อมูลชีวภาพ...',
            'hud.matching_id': 'กำลังเตรียมเข้าสู่ฐานข้อมูล...',
            'hud.redirecting_hub': 'กำลังนำคุณเข้าสู่ภารกิจ...',
            'mission.join_to_chat': 'เข้าร่วมภารกิจนี้เพื่อร่วมพูดคุยในห้องแชท',
            'mission.chat_restricted': 'ภารกิจเริ่มไปแล้ว สงวนสิทธิ์การแชทให้เฉพาะสมาชิกลูกเรือ',
            'mission.chat_closed': 'ภารกิจสิ้นสุดลงแล้ว ห้องแชทปิดให้บริการสำหรับบุคคลภายนอก',
            'mission.no_intel': 'ไม่พบข้อมูลการสื่อสาร',
            'mission.waiting_comm': 'กำลังรอการเชื่อมต่อจากเจ้าหน้าที่...',
            'hud.uplink_analysis': 'วิเคราะห์สัญญาณอัปลิงก์ // ช่องสัญญาณเข้ารหัส',
            'hud.target_location': 'พิกัดเป้าหมาย',
            'hud.intel_stream': 'เริ่มการรับส่งข้อมูลข่าวกรอง...',
            'hud.sync_orbital': 'ซิงค์วงโคจรดาวเทียม... [เรียบร้อย]',
            'hud.signal_strength': 'ระดับสัญญาณ',
            'hud.active_encryption': 'การเข้ารหัสปัจจุบัน',
            'alert.failed_send_msg': 'ส่งข้อความไม่ได้',
            'alert.failed_join': 'เข้าร่วมไม่ได้',
            'alert.failed_leave': 'ออกไม่ได้',
            'alert.mission_not_found': 'ไม่พบภารกิจ หรือภารกิจอาจถููกลบออกแล้ว',

            // New Home HUD Keys (TH)
            'home.hud.op_online': 'เจ้าหน้าที่ออนไลน์',
            'home.hud.id_token': 'รหัสประจำตัว',
            'home.hud.top_missions': 'สัญญาณภารกิจเร่งด่วน',
            'home.hud.access_all': 'เข้าถึงข้อมูลทั้งหมด',
            'home.hud.live_comms': 'ช่องสื่อสารสด',
            'home.hud.waiting_uplink': 'กำลังรอการเชื่อมต่อ...',
            'home.hud.access_denied': 'ปฏิเสธการเข้าถึง',
            'home.hud.access_denied_desc': 'ระบบเข้ารหัสทำงาน ผู้ที่ไม่มีสิทธิ์โปรดยืนยันตัวตนทันที',
            'home.hud.authorize': 'ขอยืนยันสิทธิ์',
            'home.hud.callout.op_verified': 'ยืนยันตัวตนแล้ว',
            'home.hud.callout.data_sync': 'ซิงค์ข้อมูลสำเร็จ',
            'home.hud.callout.intel_uplink': 'พิกัดข่าวกรอง',
            'home.hud.callout.signal_encrypted': 'สัญญาณถูกเข้ารหัส',
            'home.hud.guest_user': 'ผู้เยี่ยมชมระบบ',
            'home.hud.not_found': 'ไม่พบข้อมูล',

            'aar.title': 'สรุปผลภารกิจ',
            'aar.top_secret': '[เอกสารลับ]',
            'aar.authorized_by': 'คนอนุมัติ:',
            'aar.acknowledge': 'รับทราบ',
            'aar.debrief': '[สรุปงาน]',
            'aar.mission_name': 'ชื่อภารกิจ',
            'aar.final_status': 'สรุปสถานะ',
            'aar.personnel_log': '[บันทึกบุคลากร]',
            'aar.commander': 'หัวหน้าทีม',
            'aar.active_crew': 'รายชื่อทีม',
            'aar.no_crew': 'ไม่มีลูกทีม',
            'aar.hq_comms': '[ข้อความจากศูนย์]',
            'aar.success_msg': 'ทำสำเร็จแล้ว! ขอบคุณทุกคนมาก',
            'aar.failure_msg': 'ทำไม่สำเร็จ ไว้ลองใหม่คราวหน้า'
        }
    };

    constructor() {
        const saved = localStorage.getItem('lang') as Lang;
        if (saved) this.currentLang.set(saved);
    }

    toggle() {
        const next = this.currentLang() === 'en' ? 'th' : 'en';
        this.currentLang.set(next);
        localStorage.setItem('lang', next);
    }

    translate(key: string, params?: Record<string, string | number>): string {
        let text = this.dict[this.currentLang()][key] || key;
        if (params) {
            Object.keys(params).forEach(p => {
                text = text.replace(`{{${p}}}`, params[p].toString());
            });
        }
        return text;
    }
}
